//
//  EventsDataModel.swift
//  IncuLink
//
//  Created by Ankit Rajput on 30/05/24.
//

import Foundation


class EventsDataModel {
    static var event: [EventsDetail] = [
    
        EventsDetail(images: "Event1", titleNames: "India Tech Summit", dateOfEvents: "August 23, 2024", timeOfEvents: "10:00 AM to 01:00 PM", venueOfEvents: "New Delhi, India", descriptionOfEvents: "India Tech Summit is an international program featuring global speakers and partners passionate about the future of India. The central theme of the global summit is to “catalyze entrepreneurial and business ecosystems in emerging markets”. The multi-year event is a 13-year initiative of the Global Startup Ecosystem which brings together hundreds of entrepreneurs, investors, digital marketers, and creatives together in targeted cities around the world to accelerate tech, innovation, and economic development within the host country.", website: "https://allevents.in/new%20delhi/india-tech-summit/1000097765875365"),
        
        EventsDetail(images: "Event2", titleNames: "The MSME Times Excellence Awards & Business Conference 2024 : 2nd Edition", dateOfEvents: "June 29, 2024", timeOfEvents: "11:00 AM to 01:00 PM", venueOfEvents:  "New Delhi, India", descriptionOfEvents: "🏆 B2BStreets is inviting Nominations for 🏆 The MSME Times Excellence Awards & Business Conference 2024 ⭐️ B2BStreets is one of India's first Video Business Directory & helping in enhancing the reach of MSME in B2B Market.", website: "https://allevents.in/new%20delhi/the-msme-times-excellence-awards-and-business-conference-2024-2nd-edition/200026087365727?ref=eventlist-cat"),
        
        EventsDetail(images: "Event3", titleNames: "Delhi Startup Networking Event(Invite Only) by AY Ventures", dateOfEvents: "June 22, 2024", timeOfEvents: "11:00 AM to 01:00 PM", venueOfEvents: "Delhi, India", descriptionOfEvents: "Connect with the right people in a short 2-hour event with no distractions and ample time to discuss startups and the joy of solving problems. By joining this event you can find a co-founder get funding for your startup get mentorship find new clients and grow get solutions to your problems discuss new ideas/opportunities expand your network and join the AY Startup Community post the event", website: "https://allevents.in/new%20delhi/delhi-startup-networking-eventinvite-only-by-ay-ventures/80001449122384?ref=eventlist-ls-popular"),
        
        EventsDetail(images: "Event4", titleNames: "Delhi Business networking Meetup - start-ups , funding, networking", dateOfEvents: "August 21, 2024 to September 26, 2024", timeOfEvents: "12:00 AM to 12:00 AM", venueOfEvents: "New Delhi, India", descriptionOfEvents: "In this seminar we will cover a wide range of topics and provide comprehensive insights into the process of starting a business in Dubai. Our expert speakers will share their in-depth knowledge and personal experiences providing practical tips and strategies to navigate the complexities of company registration office setup and residential planning Legal Documentation Lionising. Join us to learn about the latest trends opportunities and legal requirements involved in establishing your business presence in Dubai. As well as how to ease the effort. Whether you are an experienced entrepreneur or a budding start-up this event will equip you with the necessary knowledge and resources to turn your business dreams into reality.", website: "https://allevents.in/new%20delhi/india-dubai-business-summit-delhi-learning-networking-investing-funding/80002393338447"),
        
        EventsDetail(images: "Event5", titleNames: "India Startup Summit (4th Edition) & Startup Achievers' Awards 2024", dateOfEvents: "October 04, 2024", timeOfEvents: "09:30 AM to 06:00 PM", venueOfEvents: "Radisson Blu Hotel, New Delhi Dwarka, Plot 4, Centre, Sector 13, Dwarka, New Delhi, Delhi, 110075, India", descriptionOfEvents: "INDIA STARTUP SUMMIT 2024 is the 4th edition of the annual event and an initiative by Entrepreneurs Media to join the dots among the startup community. The platform is curated to encourage the spirit of entrepreneurship among the Gen-Z hence contributing to nation-building and working towards the dream of a ‘Developed India’. ISS 2024 provides an ideal platform for the Indian Startup ecosystem to connect discuss and explore Business opportunities. Since 2021 ISS 2024 has been helping in bridging the gaps between Startup founders and Investors. ISS 2024 helps you to showcase your products and enable Face-to-face networking with potential investors co-founders and industry leaders. You will get extensive knowledge-sharing opportunities and get to learn a lot from the domain experts and fellow co-founders. Live Pitching and On-the-Spot Funding Opportunity !! A much-awaited chance to kick-start your ideas present an elevator pitch to a panel of potential investors and get funded!", website: "https://allevents.in/new%20delhi/india-startup-summit-4th-edition-and-startup-achievers-awards-2024/80003547063582"),
        
        EventsDetail(images: "Event6", titleNames: "Entrepreneur Meet Ups", dateOfEvents: "July 17, 2024", timeOfEvents: "01:00 PM to 04:00 PM", venueOfEvents: "Springhouse Coworking, Gurugram, Haryana, India", descriptionOfEvents: "If you are Looking for these all as mentioned below. So That`s the Perfect Platform for Young Entrepreneur. If you have Good Idea and looking for Co-Founder. If you already running business but facing some challenges here are the Mentors for Guidance. If you have Initial Stage of start-ups looking for Funding. Here are the perfect Platform for Pitching your Idea. Meet Like-Minded People Individuals Networking Opportunities Smart Ideation And Take feedback from the Mentors.", website: "https://allevents.in/gurgaon/entrepreneur-meet-ups/80008824015741"),
        
        EventsDetail(images: "Event7", titleNames: "India - Dubai Business Summit (Delhi) : Learning, Networking, Investing/Funding", dateOfEvents: "August 21, 2024 to September 26, 2024", timeOfEvents: "August 21, 12:00 AM to September 26, 12:00 AM", venueOfEvents: "To be updated by main, New Delhi, India", descriptionOfEvents: "Important: In our commitment to providing a productive networking environment, all tickets will undergo manual approval. This means your time will be exclusively dedicated to connecting with relevant and valuable industry contacts, enhancing the quality of interactions and opportunities. Our ethos prioritizes quality over quantity. Rather than aiming for a large crowd, we focus on curating a select group of individuals whose expertise and connections will truly enhance your networking experience.", website: "https://allevents.in/new%20delhi/india-dubai-business-summit-delhi-learning-networking-investing-funding/80002393338447"),
        
        EventsDetail(images: "Event8", titleNames: "Women Listed Bazaar: Monsoon Edition", dateOfEvents: "July 23, 2024", timeOfEvents: "05:30 AM to 02:30 PM", venueOfEvents: "Hyatt Regency Delhi, Bhikaiji Cama Place, Ring Road,Delhi, India, New Delhi", descriptionOfEvents: "One-Day Exhibition that showcases and promotes women-owned, home-grown brands where they can gain maximum and best visibility. Held at a central location in Delhi, it gives participants an opportunity to grow their businesses, connect with buyers, influencers, as well as network with each other. This Exhibition is a day of sheer indulgence where Visitors get to experience a well-curated line-up of diverse, high-quality Brands; and also show their solidarity and support for women-led businesses.", website: "https://allevents.in/new%20delhi/women-listed-bazaar-monsoon-edition/200026473057301?ref=eventlist-cat"),
        
        EventsDetail(images: "Event9", titleNames: "I-Venture Immersive (ivi) Inaugural Info Session in Delhi", dateOfEvents: "June 17, 2024", timeOfEvents: "10:00 AM to 12:00 PM", venueOfEvents: "Radisson Blu Plaza Hotel, Delhi Airport, Nh 8, New Delhi, India", descriptionOfEvents: "The Indian School of Business has launched I-Venture Immersive (ivi), an exclusive programme for aspiring first-time entrepreneurs. Join us for an interactive session with Ankur Warikoo (PGP Co ’06), founder of WebVeda, Influencer & Speaker, along with Prof. Bhagwan Chowdhry, Faculty Director, I-Venture @ ISB, to learn more about ivi. At the session, you will also: Gain insights into the application process. Get tips to prepare for the interview. Dive into the ISB campus experience. Explore scholarship opportunities. Network with the admissions team.", website: "https://allevents.in/new%20delhi/i-venture-immersive-ivi-inaugural-info-session-in-delhi-may-10-2024/10000901125589897")
    ]
}
