//
//  AllDetails.swift
//  IncuLink
//
//  Created by Krsna Sharma on 07/05/24.
//

import Foundation
import UIKit



class HomeTabData {
    static var section1a:[SuccessStories] = [
        SuccessStories(name: "EyeCan", incubationName: "Prestige Inspire Foundation", foundedYear: 2020, thumbnailURL: "success1"),
        SuccessStories(name: "KWIKPIC AI SOLUTIONS PRIVATE LIMITED", incubationName: "AIC-NMIMS INCUBATION CENTRE, MUMBAI", foundedYear: 2022, thumbnailURL: "success2"),
        SuccessStories(name: "TRAN-SCELL BIOLOGICS PRIVATE LIMITED", incubationName: "IKP LIFE SCIENCE INCUBATOR (LSI)", foundedYear: 2009, thumbnailURL: "success3"),
        SuccessStories(name: "ENTROPIK", incubationName: "Target Accelerators", foundedYear: 2016, thumbnailURL: "success4"),
        SuccessStories(name: "LEARNING MATTERS", incubationName: "AMRITA TECHNOLOGY BUSINESS INCUBATOR, KOLLAM", foundedYear: 2016, thumbnailURL: "success5"),
        SuccessStories(name: "mirrAR", incubationName: "INDIAN ANGEL NETWORK, IAN INCUBATOR", foundedYear: 2015, thumbnailURL: "success6")
    ]
    
    
    static var section1b  : [SuccessStoriesDetails] = [
        SuccessStoriesDetails(name: "EYECAN SOLUTIONS PRIVATE LIMITED", founders: "Nimish Jain , Rashi Rathore", incubationUsed: "AIC - PRESTIGE INSPIRE FOUNDATION, INDORE, APPSCALE ACADEMY", schemes: "STARTUP INDIA SEED FUND SCHEME (SISFS)", domain: "HealthTech", publicRating: 5.0, thumbnailImage: "success1"),
        SuccessStoriesDetails(name: "KWIKPIC AI SOLUTIONS PRIVATE LIMITED", founders: "HARSH KAHITAN, KUSHAL AGARWAL", incubationUsed: " AIC-NMIMS INCUBATION CENTRE MUMBAI, JITO INCUBATION AND INNOVATION FOUNDATION (JIIF), MUMBAI, SOCIETY FOR INNOVATION AND ENTREPRENEURSHIP (SINE), IIT BOMBAY", schemes: "AIC-NMIMS INCUBATION CENTRE, MUMBAI ,INCUBATION AND INNOVATION FOUNDATION (JIIF), MUMBAI, SOCIETY FOR INNOVATION AND ENTREPRENEURSHIP (SINE), IIT SINE", domain: "AI-EVENT TECH", publicRating: 4.9, thumbnailImage: "success2"),
        SuccessStoriesDetails(name: "TRAN-SCELL BIOLOGICS PRIVATE LIMITED", founders: "SUBADRA DRAVIDA", incubationUsed: "IKP LIFE SCIENCE INCUBATOR (LSI)", schemes: "BIRAC SMALL BUSINESS INNOVATION RESEARCH INITIATIVE (SBIRI) FUND, CREDIT GUARANTEE FUND TRUST FOR MICRO AND SMALL ENTERPRISES (CGTMSE) SCHEME, MINISTRY OF MSME", domain: "BioTech", publicRating: 4.4, thumbnailImage: "success3"),
        SuccessStoriesDetails(name: "ENTROPIK TECHNOLOGIES PRIVATE LIMITED", founders: "BHARAT SHEKHAWAT, LAVA KUMAR, RANJAN KUMAR", incubationUsed: "FlipKart Leap, Intel Corporation, Target Accelerators", schemes: "AXIS TRUSTEE SERVICES LIMITED", domain: "EdTech", publicRating: 3.7, thumbnailImage: "success4"),
        SuccessStoriesDetails(name: "LEARNING MATTERS PRIVATE LIMITED", founders: "GOWRI MAHESH, RAMAMOORTHY SARMA GANESA, SWARNA SARASWATHY RAMAMOORTHY", incubationUsed: "AMRITA TECHNOLOGY BUSINESS INCUBATOR KOLLAM, FISE - SOCIAL ALPHA BENGALURU, FORGE INCUBATOR -  COIMBATORE INNOVATION AND  BUSINESS INCUBATOR (CIBI), NADATHUR S RAGHAVAN CENTRE FOR ENTREPRENEURIAL LEARNING (NSRCEL), IIM BANGALORE", schemes: "DEPARTMENT OF TELECOMMUNICATIONS (DOT) 5G HACKATHON, NIDHI - ENTREPRENEUR-IN-RESIDENCE (NIDHI-EIR), DEPARTMENT OF SCIENCE AND TECHNOLOGY", domain: "EdTech", publicRating: 4.1, thumbnailImage: "success5"),
        SuccessStoriesDetails(name: "mirrAR (STYLEDOTME FASHION AND LIFESTYLE PRIVATE LIMITED)", founders: "AKHIL TOLANI, MEGHNA SARAOGI, MADHAV RAJ SARAOGI", incubationUsed: "INDIAN ANGEL NETWORK, IAN INCUBATOR", schemes: "Self Funded", domain: "Virtual Experience, Jewellery Shopping, Augmented Reality", publicRating: 4.7, thumbnailImage: "success6")
        
    ]
    // all images are available in assets
    
    static var section2a :[SchemeImage] = [SchemeImage(image: "scheme1"),SchemeImage(image: "scheme2"),SchemeImage(image: "scheme3"),SchemeImage(image: "scheme4"),SchemeImage(image: "scheme5"),SchemeImage(image: "scheme7"),SchemeImage(image: "scheme8"),SchemeImage(image: "scheme6")]
    
    static var section2b:[SchemesDetails] = [SchemesDetails(title: "STARTUP INDIA SEED FUND SCHEME (SISFS)", shortDescription: "The Startup India Seed Fund Scheme launched by the Ministry of Commerce & Industry, was established with the primary goal of offering financial support to startups at various crucial stages of their development journey. This support spans from helping them create proof of concept and prototypes to conducting product trials, entering the market, and eventually achieving commercial success. One of the key advantages of the SISFS scheme is that it offers startups the opportunity to access critical funding without the burden of high- interest loans. By doing so, it helps reduce the financial risk associated with early-stage ventures. The STARTUP INDIA SEED FUND SCHEME (SISFS) is open to a wide range of startup niches and sectors. It does not limit its support to specific industries, making it versatile and adaptable to the diverse needs of innovative ventures. This inclusivity ensures that startups from various domains, such as technology, healthcare, agriculture, and more, can benefit from the fund's assistance as they work towards realizing their entrepreneurial visions.", startupSupported: "610", websiteLink: "https://seedfund.startupindia.gov.in/?ref=ynos.in", thumbnailImage: "scheme1"),
    SchemesDetails(title: "IFCI VENTURE CAPITAL FUND FOR SCHEDULED CASTES", shortDescription: "The 'IFCI Venture Capital Fund for Scheduled Castes' was established by the Ministry of Social Justice and Empowerment, Government of India, with the primary aim of fostering entrepreneurship within the scheduled castes community. This fund plays a crucial role in supporting startups, incubators, and accelerators belonging to scheduled castes, empowering them to transform innovative ideas into successful businesses. On average, this fund provides concessional financial support to eligible beneficiaries. The exact amount may vary depending on the specific business proposal and its viability, but the fund strives to make capital accessible to enable the growth of scheduled caste entrepreneurs. Entrepreneurs and businesses benefit from several perks through this fund. These include financial assistance at favorable terms, which can include lower interest rates and flexible repayment options. Prominent investment areas or niches supported by the IFCI Venture Capital Fund for Scheduled Castes encompass a wide range of sectors, including technology, agriculture, manufacturing, and service industries.", startupSupported: "115", websiteLink: "https://www.vcfsc.in/index.html?ref=ynos.in", thumbnailImage: "scheme2"),
    SchemesDetails(title: "RKVY- RAFTAAR AGRI-ENTREPRENEURSHIP PROGRAMME, MINISTRY OF AGRICULTURE AND FARMERS' WELFAR", shortDescription: "The 'RKVY-RAFTAAR Agri-Entrepreneurship Programme' was established with the primary aim of fostering innovation and agripreneurship within the agricultural and allied sectors. This initiative seeks to provide vital financial support and cultivate a robust incubation ecosystem. Here's a breakdown of key aspects of the program: The Rkvy-Raftaar scheme is immensely beneficial for aspiring agripreneurs, including startups, incubators, and accelerators. It offers crucial financial support at both the idea/pre-seed stage (Rs. 5.00 lakh) and the seed stage (Rs. 25 lakh), making it accessible to a wide range of innovators. On average, this fund provides Rs. 5.00 lakh for initial idea development and Rs. 25 lakh for the subsequent seed stage. This financial backing helps entrepreneurs turn their concepts into viable businesses. Entrepreneurs who avail themselves of this fund gain access to essential financial resources that enable them to bring their agricultural innovations to life. Additionally, they benefit from the support and guidance of the incubation ecosystem, which can significantly enhance their chances of success.", startupSupported: "426", websiteLink: "https://rkvystartups.nic.in/?ref=ynos.in", thumbnailImage: "scheme3"),
    SchemesDetails(title: "TECHNOLOGY DEVELOPMENT BOARD, DEPARTMENT OF SCIENCE & TECHNOLOGY", shortDescription: "The Technology Development Board (TDB), under the Department of Science & Technology, was established to provide financial assistance and support to Indian industrial concerns and organizations engaged in the development and commercial application of technology, whether indigenous or adapted from imported sources. This fund is beneficial for a wide range of stakeholders, including startups, industrial concerns, research and development (R&D) institutions, and agencies involved in technology development and commercialization. It is particularly valuable for small enterprises seeking support for their innovative ideas and projects. TDB focuses on various technology priorities for India, including modernizing and reducing costs in infrastructure sectors like energy, transport, housing, and communication. It also supports technology development in sectors driving exports to enhance value-addition and improve export quality and quantity. Technology Development Board India works on frontier market-oriented technologies where India can make an impact and attain a globally competitive edge.", startupSupported: "85", websiteLink: "https://tdb.gov.in/?ref=ynos.in", thumbnailImage: "scheme4"),
    SchemesDetails(title: "BIRAC BIOTECHNOLOGY INDUSTRY PARTNERSHIP PROGRAMME (BIPP)", shortDescription: "The BIRAC Biotechnology Industry Partnership Programme (BIPP), established by the Biotechnology Industry Research Assistance Council (BIRAC), serves as a vital platform to empower emerging biotech enterprises in India. This fund is primarily beneficial for biotech startups and SMEs in India, offering support for high-risk, breakthrough technologies and processes. The funding amount provided by BIPP varies according to each project's specific requirements, ensuring that innovative ideas with transformative potential receive the necessary financial backing. The Biotechnology Industry Partnership Programme offers numerous advantages, including access to risk capital, technology transfer, intellectual property management, and expert guidance throughout the innovation journey. The program fosters innovation and entrepreneurship, promotes affordable product development, and encourages collaboration with partners to enhance capabilities and facilitate the commercialization of discoveries. Proposals are invited under seven broad themes, encompassing diverse biotechnology areas such as drugs, vaccines, biosimilars, agriculture, and bioinformatics, among others. BIPP focuses on advanced technology projects with high-risk and transformative potential, supporting breakthrough research endeavors.", startupSupported: "93", websiteLink: " https://birac.nic.in/desc_new.php?ref=ynos.in", thumbnailImage: "scheme5"),
    SchemesDetails(title: "INNOVATIONS FOR DEFENCE EXCELLENCE (IDEX) SPARK GRANTS, MINISTRY OF DEFENCE", shortDescription: "The IDEX (IDEX full form: Innovations for Defence Excellence) Spark Grants, initiated by the Ministry of Defence, Government of India, aim to cultivate an environment conducive to innovation and technology advancement in the Defense and Aerospace sectors. The fund supports research and development with the potential for future adoption by the Indian defense and aerospace industries. The IDEX Spark Grants serve as a valuable resource for startups, MSMEs, individual innovators, and incubators in the field of defense and aerospace. IDEX India encourages open innovation, inviting Indian innovators and entrepreneurs to provide technologically advanced solutions to meet the needs of the Indian military. Selected applicants, based on their capability and potential to produce functional prototypes or commercialize existing technologies, can receive grants of up to Rs. 1.5 crores. These grants are provided on a milestone basis and can take the form of grants, equity, debt, or other relevant structures. The focus of this framework is on developing prototypes and bringing products/technologies to market, primarily in the defense sector.", startupSupported: "245", websiteLink: "https://idex.gov.in/?ref=ynos.in", thumbnailImage: "scheme7"),
    SchemesDetails(title: "SIDBI VENTURE CAPITAL LIMITED, MUMBAI", shortDescription: "SIDBI Venture Capital Limited (SVCL) was established with the primary objective of fostering economic growth and development in India. This fund serves as an investment management company and is a subsidiary of the Small Industries Development Bank of India (SIDBI). SVCL plays a pivotal role in supporting various segments of the economy, making it a versatile resource for a wide range of stakeholders. Startups, early-stage technology businesses, manufacturing SMEs (Small and Medium Enterprises), service entities, agri- businesses, and financial inclusion companies are the key beneficiaries of SVCL's funding initiatives. The fund doesn't have a fixed average funding amount, as it manages various funds targeting different sectors and stages of businesses. Funding is typically tailored to the specific needs and potential of each applicant. Entrepreneurs and businesses availing SVCL's support gain access to several perks. These include not only the necessary capital but also strategic guidance, mentorship, and networking opportunities. SVCL's extensive experience and industry connections can help businesses grow and thrive.", startupSupported: "46", websiteLink: "https://sidbiventure.co.in/?ref=ynos.in", thumbnailImage: "scheme8"),
    SchemesDetails(title: "NIDHI - PROMOTING AND ACCELERATING YOUNG AND ASPIRING TECHNOLOGY ENTREPRENEURS (NIDHI-PRAYAS), DEPARTMENT OF SCIENCE AND TECHNOLOGY", shortDescription: "NIDHI-PRAYAS (Promoting and Accelerating Young and Aspiring Technology Entrepreneurs) is a flagship initiative by the Department of Science and Technology (DST), Government of India. This program aims to foster innovation and entrepreneurship among young and aspiring technologists. By providing crucial early-stage support, NIDHI-PRAYAS helps individuals transform their innovative ideas into viable prototypes. The program offers financial assistance up to INR 10 lakhs, enabling entrepreneurs to develop prototypes, conduct market research, and validate their product concepts. In addition to funding, NIDHI-PRAYAS provides access to state-of-the-art incubation facilities, mentorship from industry experts, and networking opportunities with potential investors and business partners. This comprehensive support system is designed to address the challenges faced by early-stage startups, reducing the time and cost of product development. This initiative reflects the government's commitment to promoting entrepreneurship and positioning India as a global leader in technology and innovation.", startupSupported: "629", websiteLink: "https://nidhi-prayas.org/?ref=ynos.in#parentVerticalTab11", thumbnailImage: "scheme6")
    ]
    
    
    
    
    
    static var section3a: [IncubationCentreList] = [
               IncubationCentreList(name: "TECHNOLOGY BUSINESS INCUBATOR (TBI) AT UNIVERSITY OF HYDERABAD", incubatedStartup: 19, thumbnailURL: "incu1", latitude: 17.4584, longitude: 78.3498),
               IncubationCentreList(name: "IKP LIFE SCIENCE INCUBATOR (LSI)", incubatedStartup: 64, thumbnailURL: "incu2", latitude: 17.4472, longitude: 78.3776),
               IncubationCentreList(name: "VENTURE CENTER, PUNE", incubatedStartup: 113, thumbnailURL: "incu3", latitude: 18.5382, longitude: 73.8076),
               IncubationCentreList(name: "CENTRE FOR INCUBATION AND BUSINESS ACCELERATION, MUMBAI", incubatedStartup: 56, thumbnailURL: "incu4", latitude: 19.0595, longitude: 72.8302),
               IncubationCentreList(name: "INDIGRAM LABS FOUNDATION, DELHI", incubatedStartup: 72, thumbnailURL: "incu5", latitude: 28.5450, longitude: 77.1707),
               IncubationCentreList(name: "AIC PINNACLE ENTREPRENEURSHIP FORUM, PUNE", incubatedStartup: 21, thumbnailURL: "incu6", latitude: 18.5186, longitude: 73.9272),
               IncubationCentreList(name: "PDPU INNOVATION AND INCUBATION CENTRE (PDPU IIC)", incubatedStartup: 53, thumbnailURL: "incu7", latitude: 23.1717, longitude: 72.6417),
               IncubationCentreList(name: "AIC-EMPI INCUBATION FOUNDATION,DELHI", incubatedStartup: 17, thumbnailURL: "incu8", latitude: 28.6506, longitude: 77.2303),
               IncubationCentreList(name: "INDIAN ANGEL NETWORK, IAN INCUBATOR", incubatedStartup: 44, thumbnailURL: "incu9", latitude: 28.6139, longitude: 77.2090),
               IncubationCentreList(name: "TARGET ACCELERATORS", incubatedStartup: 39, thumbnailURL: "incu10", latitude: 12.9716, longitude: 77.5946),
               IncubationCentreList(name: "AMRITA TECHNOLOGY BUSINESS INCUBATOR, KOLLAM", incubatedStartup: 60, thumbnailURL: "incu11", latitude: 8.8932, longitude: 76.6141),
               IncubationCentreList(name: "SHIV NADAR AIC RESEARCH FOUNDATION", incubatedStartup: 24, thumbnailURL: "incu12", latitude: 28.4744, longitude: 77.5037),
               IncubationCentreList(name: "JSS STEP-BUSINESS INCUBATOR, NOIDA", incubatedStartup: 23, thumbnailURL: "incu13", latitude: 28.5355, longitude: 77.3910),
               IncubationCentreList(name: "STARTUP INCUBATION AND INNOVATION CENTRE, IIT KANPUR", incubatedStartup: 342, thumbnailURL: "incu15", latitude: 26.5145, longitude: 80.2329)
           ]
    
    
    static var section3b:[IncubationCentreDetails] = [
        IncubationCentreDetails(name: "TECHNOLOGY BUSINESS INCUBATOR (TBI) AT UNIVERSITY OF HYDERABAD", established: 2008, numberOfStartupsIncubated: 19, recognizedAndFundedBy: "BIRAC BIOTECHNOLOGY IGNITION GRANT (BIG)", location: "Hyderabad", thumbnailImage: "incu1",latitude: 17.4584 ,longitude: 78.3498 ),
        IncubationCentreDetails(name: "IKP LIFE SCIENCE INCUBATOR (LSI)", established: 2006, numberOfStartupsIncubated: 64, recognizedAndFundedBy: "Department of Science & Technology (DST), Ministry of Electronics and Information Technology (MeitY)", location: "Hyderabad", thumbnailImage: "incu2", latitude:  17.4472, longitude: 78.3776),
        IncubationCentreDetails(name: "VENTURE CENTER, PUNE", established: 2007, numberOfStartupsIncubated: 113, recognizedAndFundedBy: "Department of Biotechnology (DBT), Department of Science & Technology (DST), Ministry of Defence (MoD)", location: "Pune", thumbnailImage: "incu3", latitude: 18.5382, longitude: 73.8076),
        IncubationCentreDetails(name: "CENTRE FOR INCUBATION AND BUSINESS ACCELERATION, MUMBAI", established: 2012, numberOfStartupsIncubated: 56, recognizedAndFundedBy: "Department of Science & Technology (DST)", location: "Mumbai", thumbnailImage: "incu4", latitude: 19.0595, longitude: 72.8302 ),
        IncubationCentreDetails(name: "INDIGRAM LABS FOUNDATION, DELHI", established: 2015, numberOfStartupsIncubated: 72, recognizedAndFundedBy: "Department of Biotechnology (DBT), Department of Science & Technology (DST), Ministry of Micro, Small and Medium Enterprises (MSME), Startup India Seed Fund Scheme (SISFS)", location: "Delhi", thumbnailImage: "incu5", latitude: 28.5450, longitude:  77.1707),
        IncubationCentreDetails(name: "AIC PINNACLE ENTREPRENEURSHIP FORUM, PUNE", established: 2019, numberOfStartupsIncubated: 21, recognizedAndFundedBy: "Atal Innovation Mission (AIM), Ministry of Electronics and Information Technology (MeitY), Ministry of Micro, Small and Medium Enterprises (MSME)", location: "Pune", thumbnailImage: "incu6", latitude: 18.5186, longitude: 73.9272),
        IncubationCentreDetails(name: "PDPU INNOVATION AND INCUBATION CENTRE (PDPU IIC)", established: 2014, numberOfStartupsIncubated: 53, recognizedAndFundedBy: "Department of Science & Technology (DST), Startup India Seed Fund Scheme (SISFS)", location: "Ahmedabad", thumbnailImage: "incu7",latitude: 23.1717 , longitude: 72.6417),
        IncubationCentreDetails(name: "AIC-EMPI INCUBATION FOUNDATION,DELHI", established: 2018, numberOfStartupsIncubated: 17, recognizedAndFundedBy: "Atal Innovation Mission (AIM)", location: "Delhi",thumbnailImage: "incu8", latitude: 28.6506, longitude: 77.2303),
        IncubationCentreDetails(name: "INDIAN ANGEL NETWORK, IAN INCUBATOR", established: 2006, numberOfStartupsIncubated: 44, recognizedAndFundedBy: "Department of Science & Technology (DST)", location: "Delhi", thumbnailImage: "incu9", latitude: 28.6139, longitude: 77.2090),
        IncubationCentreDetails(name: "TARGET ACCELERATORS", established: 2014, numberOfStartupsIncubated: 39, recognizedAndFundedBy: "HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, AXIS TRUSTEE SERVICES LIMITED, HDFC BANK LIMITED", location: "Bengaluru", thumbnailImage: "incu10",latitude:  12.9716, longitude: 77.5946),
        IncubationCentreDetails(name: "AMRITA TECHNOLOGY BUSINESS INCUBATOR, KOLLAM", established: 2008, numberOfStartupsIncubated: 60, recognizedAndFundedBy: "Atal Innovation Mission (AIM), Department of Science & Technology (DST), Ministry of Electronics and Information Technology (MeitY), Ministry of Micro, Small and Medium Enterprises (MSME)", location: "KOLLAM", thumbnailImage: "incu11", latitude:  8.8932,longitude: 76.6141),
        IncubationCentreDetails(name: "SHIV NADAR AIC RESEARCH FOUNDATION", established: 2017, numberOfStartupsIncubated: 24, recognizedAndFundedBy: "Atal Innovation Mission (AIM) , Startup India Seed Fund Scheme (SISFS)", location: "Noida", thumbnailImage: "incu12", latitude: 28.4744, longitude: 77.5037),
        IncubationCentreDetails(name: "JSS STEP-BUSINESS INCUBATOR, NOIDA", established: 2018, numberOfStartupsIncubated: 23, recognizedAndFundedBy: "Department of Science & Technology (DST)", location: "Noida", thumbnailImage: "incu13", latitude: 28.5355, longitude: 77.3910),
        IncubationCentreDetails(name: "STARTUP INCUBATION AND INNOVATION CENTRE, IIT KANPUR", established: 2003, numberOfStartupsIncubated: 342, recognizedAndFundedBy: "Department of Biotechnology (DBT), Department of Science & Technology (DST), Ministry of Defence (MoD), Ministry of Electronics and Information Technology (MeitY), Ministry of Micro, Small and Medium Enterprises (MSME), Startup India Seed Fund Scheme (SISFS)", location: "Kanpur",thumbnailImage: "incu15" ,latitude: 26.5145, longitude: 80.2329)
        
               
        
            
        
    ]
    
    
    static var sectionHeaders: [String] = ["Success Stories", "Schemes","List Of Incubators"]
}


